name: Check changes
description: Deduce required tests from code changes
inputs:
  filters_path:
    required: true
    description: ''
outputs:
  tested:
    description: "true if the tests should be executed"
    value: ${{ steps.tested-tree.outputs.src }}
  head_sha:
    description: "HEAD commit sha"
    value: ${{ steps.tested-tree.outputs.src }}
runs:
  using: composite
  steps:
    # Because we run on issue comments, we need to checkout the code for
    # paths-filter to work.
    - name: Checkout code
      if: ${{ github.event.issue.pull_request }}
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        persist-credentials: false

    - name: Retrieve pull request's base and head
      id: pr
      shell: bash
      run: |
        if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
          curl ${{ github.event.issue.pull_request.url }} > pr.json
          echo "base=$(jq -r '.base.sha' pr.json)" >> $GITHUB_OUTPUT
          echo "head=$(jq -r '.head.sha' pr.json)" >> $GITHUB_OUTPUT

    - name: Check code changes
      if: ${{ github.event.issue.pull_request }}
      uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: tested-tree
      with:
        base: ${{ steps.pr.outputs.base }}
        ref: ${{ steps.pr.outputs.head }}
        # Path to file where filters are defined
        filters: ${{ inputs.filters_path }}
