name: Images legacy

on:
  pull_request_target:
    types:
      - labeled
  push:
    branches:
      - master
      - v1.9
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  multi-registries:
    runs-on: ubuntu-20.04
    if: github.repository == 'aanm/cilium' && contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Hackerman!
        run: |
           echo ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::pr-test-docker-images-legacy
      - name: Build Cilium Operator
        id: docker_build_operator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cilium-operator.Dockerfile
          push: true
          cache-from: ${{ github.repository_owner }}/operator-dev:cache-build-${{ steps.vars.outputs.tag }}
          cache-to: mode=max,type=registry,ref=${{ github.repository_owner }}/operator-dev:cache-build-${{ steps.vars.outputs.tag }}
          tags: |
            ${{ github.repository_owner }}/operator-dev:${{ github.event.pull_request.head.sha }}
            ${{ github.repository_owner }}/operator-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/operator-dev:${{ github.event.pull_request.head.sha }}
            quay.io/${{ github.repository_owner }}/operator-dev:${{ steps.vars.outputs.tag }}
      - name: Image digests
        run: |
          echo "::group::Image digests"
          echo "Official Docker Image Repositories: docker.io, quay.io"
          echo "Cilium Operator: ${{ steps.docker_build_operator.outputs.digest }}"
          echo "::endgroup::"
