name: Always Succeed

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  always_succeed_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a successful command
        run: echo "This will succeed"

      - name: Randomly fail 50% of the time
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Random failure occurred!"
            exit 1
          else
            echo "Lucky! This time it succeeded."
          fi

      - name: Generate sponge_log.xml for flakybot
        if: always()
        run: |
          mkdir -p test-results
          cat > test-results/sponge_log.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuites>
            <testsuite name="always_succeed_job" tests="2" failures="${{ job.status == 'failure' && '1' || '0' }}" errors="0" time="1.0">
              <testcase name="Run a successful command" classname="always_succeed_job" time="0.1">
              </testcase>
              <testcase name="Randomly fail 50% of the time" classname="always_succeed_job" time="0.9">
                ${{ job.status == 'failure' && '<failure message="Random failure occurred!" type="RandomFailure">Random failure occurred!</failure>' || '' }}
              </testcase>
            </testsuite>
          </testsuites>
          EOF

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/sponge_log.xml

  rerun-on-failure:
    needs: always_succeed_job
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run ci-re-run.yaml -F run_id=${{ github.run_id }}
